---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : raymond
production_url : http://aartisan.github.io

posts:
  permalink: /:categories/:title/
  summary_lines: 13
  latest: 8

pages:
  permalink: 'pretty'
