title : Ray's Blog
tagline: 记录生活点滴故事
author :
  name : Ray
  email : ray.artisan@gmail.com
  github : Aartisan

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
